// ============================================================
// build.js — Vercel 构建脚本
// 从环境变量生成 config.local.js，保护密钥安全
// ============================================================
const fs = require('fs');
const path = require('path');

const config = {
  SUPABASE_URL: process.env.SUPABASE_URL || 'https://your-project.supabase.co',
  SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY || 'your-anon-key'
};

const content = `// Auto-generated by build.js — do not edit manually
window.__MB_CONFIG__ = {
  SUPABASE_URL: '${config.SUPABASE_URL}',
  SUPABASE_ANON_KEY: '${config.SUPABASE_ANON_KEY}'
};
`;

fs.writeFileSync(path.join(__dirname, 'config.local.js'), content);
console.log('✅ config.local.js generated from environment variables');
